config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  scope '/admin' do
    devise_for :users, skip: [:registrations], controllers: { sessions: 'users/sessions' }

    devise_scope :user do
      get 'users/sign_up', to: 'devise/registrations#new'
      post 'users/sign_up', to: 'devise/registrations#create'
      get 'profile/password', to: 'devise/registrations#edit'
      patch 'profile/password', to: 'devise/registrations#update'
      put 'profile/password', to: 'devise/registrations#update'
      delete 'profile', to: 'devise/registrations#destroy'
    end
  end

  namespace :admin do
    root to: 'dashboard#index'

    resources :profile, only: [] do
      collection do
        get '', to: 'profile#show'
        
        get 'avatar', to: 'profile#edit_avatar'
        patch 'avatar', to: 'profile#update_avatar'
        put 'avatar', to: 'profile#update_avatar'

        get 'edit', to: 'profile#edit'
        put '', to: 'profile#update'
        patch '', to: 'profile#update'
      end
    end

    resources :users, except: [:show] do
      member do
        get '', to: 'users#show', constraints: { id: /\d+/ }, as: :user
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/profile_controller.rb
class Admin::ProfileController < ApplicationController
  def show
  end

  def update
    if current_user.update(user_params)
      flash[:notice] = 'Profile updated'
      respond_to do |format|
        format.html {
          redirect_to profile_path
        }
        format.turbo_stream { render :update } # Render the Turbo Stream view
      end
    else
      respond_to do |format|
        format.html {
          render :edit
        }
        format.turbo_stream { render :update } # Render the Turbo Stream view
      end
    end
  end

  def edit
  end

  def edit_avatar
  end

  def update_avatar
    if params[:remove_avatar].present?
      handle_remove_avatar
      return
    end

    if avatar_params[:avatar].blank?
      current_user.errors.add(:avatar, 'cannot be blank')
      render_error_update_avatar
      return
    end

    # avatar = resize_avatar(avatar_params[:avatar])
    avatar = avatar_params[:avatar]
    current_user.profile_avatar.attach(avatar)

    if current_user.save
      flash[:notice] = 'Avatar updated'
      respond_to do |format|
        format.html {
          redirect_to profile_avatar_path
        }
        format.turbo_stream { render :update_avatar } # Render the Turbo Stream view
      end

      return
    end

    render_error_update_avatar
  end

  private

  def handle_remove_avatar
    begin
      current_user.profile_avatar.purge
      flash[:notice] = 'Avatar removed'
      respond_to do |format|
        format.html {
          redirect_to profile_avatar_path
        }
        format.turbo_stream { render :update_avatar } # Render the Turbo Stream view
      end
    rescue => e
      current_user.errors.add(:avatar, 'could not be removed')
      render_error_update_avatar
    end
  end

  def render_error_update_avatar
    respond_to do |format|
      format.html {
        render :edit_avatar
      }
      format.turbo_stream { render :update_avatar } # Render the Turbo Stream view
    end
  end

  def user_params
    params.fetch(:user, {}).permit(:email, :first_name, :last_name, :phone_number, :birth_date)
  end

  def avatar_params
    params.fetch(:user, {}).permit(:avatar)
  end

  # def resize_avatar(avatar)
  #   io = MiniMagick::Image.read(avatar.tempfile)
  #   io.resize "300x300>"
  #   io = StringIO.new(io.to_blob) # Convert to StringIO for re-upload
  #   io.set_encoding('BINARY') # Ensure binary encoding is set
  #   io
  # end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  end

  def update
    if current_user.update(user_params)
      flash[:notice] = 'Profile updated'
      respond_to do |format|
        format.html {
          redirect_to profile_path
        }
        format.turbo_stream { render :update } # Render the Turbo Stream view
      end
    else
      respond_to do |format|
        format.html {
          render :edit
        }
        format.turbo_stream { render :update } # Render the Turbo Stream view
      end
    end
  end

  def edit
  end

  def edit_avatar
  end

  def update_avatar
    if params[:remove_avatar].present?
      handle_remove_avatar
      return
    end

    if avatar_params[:avatar].blank?
      current_user.errors.add(:avatar, 'cannot be blank')
      render_error_update_avatar
      return
    end

    # avatar = resize_avatar(avatar_params[:avatar])
    avatar = avatar_params[:avatar]
    current_user.profile_avatar.attach(avatar)

    if current_user.save
      flash[:notice] = 'Avatar updated'
      respond_to do |format|
        format.html {
          redirect_to profile_avatar_path
        }
        format.turbo_stream { render :update_avatar } # Render the Turbo Stream view
      end

      return
    end

    render_error_update_avatar
  end

  private

  def handle_remove_avatar
    begin
      current_user.profile_avatar.purge
      flash[:notice] = 'Avatar removed'
      respond_to do |format|
        format.html {
          redirect_to profile_avatar_path
        }
        format.turbo_stream { render :update_avatar } # Render the Turbo Stream view
      end
    rescue => e
      current_user.errors.add(:avatar, 'could not be removed')
      render_error_update_avatar
    end
  end

  def render_error_update_avatar
    respond_to do |format|
      format.html {
        render :edit_avatar
      }
      format.turbo_stream { render :update_avatar } # Render the Turbo Stream view
    end
  end

  def user_params
    params.fetch(:user, {}).permit(:email, :first_name, :last_name, :phone_number, :birth_date)
  end

  def avatar_params
    params.fetch(:user, {}).permit(:avatar)
  end

  # def resize_avatar(avatar)
  #   io = MiniMagick::Image.read(avatar.tempfile)
  #   io.resize "300x300>"
  #   io = StringIO.new(io.to_blob) # Convert to StringIO for re-upload
  #   io.set_encoding('BINARY') # Ensure binary encoding is set
  #   io
  # end
end

app/helpers/profile_helper.rb
module ProfileHelper
  def short_name(full_name = nil)
    return 'Avatar' if full_name.nil? || full_name.strip.empty?  # Return empty string for nil or empty input
    
    # Split the full name into parts by spaces
    name_parts = full_name.split
    
    # Take the first letter of each part, convert to uppercase, and join them
    short_name = name_parts.map { |part| part[0].upcase }.join
    
    short_name
  end
end

app/views/admin/profile/_avatar_form.html.erb
<%= turbo_frame_tag "profile_form" do %>
  <% is_uploaded_avatar = current_user.profile_avatar_attachment&.blob.present? %>

  <%= render "admin/profile/current_avatar" %>

  <%= form_for(current_user, url: avatar_admin_profile_index_path,
    html: { method: :patch }, data: { turbo: true }, class: 'mx-auto max-w-xs') do |f| %>
    <%= render "devise/shared/error_messages", resource: current_user %>
    <%= hidden_field_tag :remove_avatar %>

    <div class='my-3'>
      <label for='user_avatar'
        class="bg-white dark:bg-gray-300 text-gray-500 font-semibold text-base rounded h-52 flex flex-col items-center justify-center cursor-pointer border-2 border-gray-300 dark:border-gray-600 border-dashed mx-auto font-[sans-serif]">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-11 mb-2 fill-gray-500" viewBox="0 0 32 32">
          <path
            d="M23.75 11.044a7.99 7.99 0 0 0-15.5-.009A8 8 0 0 0 9 27h3a1 1 0 0 0 0-2H9a6 6 0 0 1-.035-12 1.038 1.038 0 0 0 1.1-.854 5.991 5.991 0 0 1 11.862 0A1.08 1.08 0 0 0 23 13a6 6 0 0 1 0 12h-3a1 1 0 0 0 0 2h3a8 8 0 0 0 .75-15.956z"
            data-original="#000000" />
          <path
            d="M20.293 19.707a1 1 0 0 0 1.414-1.414l-5-5a1 1 0 0 0-1.414 0l-5 5a1 1 0 0 0 1.414 1.414L15 16.414V29a1 1 0 0 0 2 0V16.414z"
            data-original="#000000" />
        </svg>
        Upload file

        <%= f.file_field :avatar, class: "hidden" %>
        <p class="text-xs font-medium text-gray-400 mt-2">PNG, JPG and JPEG are Allowed.</p>
        <p class="text-xs font-medium text-gray-400">Max size of 5MB</p>
      </label>
    </div>

    <div class='mt-5 tracking-wide flex max-[360px]:flex-col flex-row justify-between w-full'>
      <button type='submit' class="<%= is_uploaded_avatar ? nil : 'w-full ' %>font-semibold bg-indigo-500 p-4 text-gray-100 rounded-lg hover:bg-indigo-700 transition-all duration-300 ease-in-out flex items-center justify-center focus:shadow-outline focus:outline-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-bounding-box" viewBox="0 0 16 16">
          <path d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5M.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5m15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5"/>
          <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
        </svg>
        <span class="ml-3">Update</span>
      </button>

      <% if is_uploaded_avatar %>
        <button type='button' onclick='removeAvatarHandle()'
          class="max-[360px]:mt-2 mt-0 font-semibold bg-red-500 p-4 text-gray-100 rounded-lg hover:bg-red-700 transition-all duration-300 ease-in-out flex items-center justify-center focus:shadow-outline focus:outline-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
          </svg>
          <span class="ml-3">Remove</span>
        </button>
      <% end %>
    </div>
  <% end %>

  <div class='mt-6 text-xs text-gray-600 text-center justify-between'>
    <div class='flex justify-between'>
      <%= link_to 'Change Password', profile_password_path, class: 'text-gray-900 hover:text-blue-700 dark:text-white dark:hover:text-blue-500 dark:hover:text-blue-500 hover:underline', data: { turbo_frame: '_top' } %>
      <%= link_to 'Update Profile', edit_admin_profile_index_path, class: 'text-gray-900 hover:text-blue-700 dark:text-white dark:hover:text-blue-500 dark:hover:text-blue-500 hover:underline', data: { turbo_frame: '_top' } %>
    </div>

    <%= link_to 'Back', profile_path, class: 'dark:text-white dark:hover:text-blue-500 dark:hover:text-blue-500 hover:underline text-indigo-600 hover:text-indigo-800', data: { turbo_frame: '_top' } %>
  </div>

  <% if is_uploaded_avatar %>
    <%= javascript_tag do %>
      function removeAvatarHandle() {
        if (confirm('Are you sure you want to remove your avatar?')) {
          const hiddenField = document.querySelector('#remove_avatar');
          if (hiddenField) {
            hiddenField.value = '1';
            hiddenField.closest('form').submit();
          }
        }
      };
    <% end %>
  <% end %>

<% end %>

app/views/admin/profile/_current_avatar.html.erb
<% if current_user.profile_avatar.attached? %>
  <% if current_user.profile_avatar.persisted? %>
    <%= image_tag current_user.profile_avatar, class: 'rounded-lg' %>
  <% elsif current_user.profile_avatar_attachment&.blob %>
    <p class='mb-2'>Avatar is invalid. Your old avatar is still being used.</p>
    <%= render 'admin/profile/uploaded_avatar_info' %>
    <%= image_tag current_user.profile_avatar_attachment, class: 'rounded-lg' %>
  <% else %>
    <p class='mb-2'>Avatar is invalid.</p>
    <%= render 'admin/profile/uploaded_avatar_info' %>
  <% end %>
<% else %>
  <p class='mb-2'>No avatar uploaded.</p>
<% end %>

app/views/admin/profile/_form.html.erb
<%= turbo_frame_tag "profile_form" do %>
  <%= form_for(current_user, url: profile_path, html: { method: :patch }) do |f| %>
    <%= render "devise/shared/error_messages", resource: current_user %>

    <div class='mb-3'>
      <%= f.label :email, class: 'block dark:text-gray-200 text-gray-700 text-sm mb-2' %>
      <%= f.email_field :email, autofocus: true, placeholder: "Email",
        class: 'w-full px-8 py-4 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white' %>
      
      <div class="mt-5 flex flex-col max-[430px]:space-x-0 max-[430px]:flex-col max-md:flex-row max-md:space-x-5 min-[930px]:flex-row min-[930px]:space-x-5">
        <div class="flex-1">
          <%= f.label :first_name, class: 'block dark:text-gray-200 text-gray-700 text-sm mb-2' %>
          <%= f.text_field :first_name, placeholder: "First Name",
            class: "w-full px-8 py-4 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white" %>
        </div>

        <div class="flex-1 mt-5 max-[430px]:mt-5 max-md:mt-0 min-[930px]:mt-0">
          <%= f.label :last_name, class: 'block dark:text-gray-200 text-gray-700 text-sm mb-2' %>
          <%= f.text_field :last_name, placeholder: "Last Name",
            class: "w-full px-8 py-4 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white" %>
        </div>
      </div>

      <div class="mt-5 flex flex-col max-[430px]:space-x-0 max-[430px]:flex-col max-md:flex-row max-md:space-x-5 min-[930px]:flex-row min-[930px]:space-x-5">
        <div class="flex-1">
          <%= f.label :phone_number, class: 'block dark:text-gray-200 text-gray-700 text-sm mb-2' %>
          <%= f.text_field :phone_number, placeholder: "Phone Number",
            class: "w-full px-8 py-4 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white" %>
        </div>
        <div class="flex-1 mt-5 max-[430px]:mt-5 max-md:mt-0 min-[930px]:mt-0">
          <%= f.label :birth_date, class: 'block dark:text-gray-200 text-gray-700 text-sm mb-2' %>
          <%= f.date_field :birth_date, placeholder: "Birth Date",
            class: "w-full px-8 py-4 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white" %>
        </div>
      </div>
    </div>

    <button type='submit' class="mt-5 tracking-wide font-semibold bg-indigo-500 text-gray-100 w-full py-4 rounded-lg hover:bg-indigo-700 transition-all duration-300 ease-in-out flex items-center justify-center focus:shadow-outline focus:outline-none">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-floppy-fill" viewBox="0 0 16 16">
        <path d="M0 1.5A1.5 1.5 0 0 1 1.5 0H3v5.5A1.5 1.5 0 0 0 4.5 7h7A1.5 1.5 0 0 0 13 5.5V0h.086a1.5 1.5 0 0 1 1.06.44l1.415 1.414A1.5 1.5 0 0 1 16 2.914V14.5a1.5 1.5 0 0 1-1.5 1.5H14v-5.5A1.5 1.5 0 0 0 12.5 9h-9A1.5 1.5 0 0 0 2 10.5V16h-.5A1.5 1.5 0 0 1 0 14.5z"/>
        <path d="M3 16h10v-5.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5zm9-16H4v5.5a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5zM9 1h2v4H9z"/>
      </svg>
      <span class="ml-3">Update</span>
    </button>
  <% end %>
<% end %>

app/views/admin/profile/edit.html.erb
<div class="max-w-screen-xl mx-auto md:bg-red-200 shadow sm:rounded-lg flex justify-center flex-1">
  <div class="rounded-e-lg rounded-s-lg md:rounded-e-none md:w-1/2 w-full xl:w-5/12 dark:bg-gray-600 bg-white p-4 md:p-6 sm:p-12">
    <div class="mt-3 flex flex-col items-center">
      <h1 class="text-2xl xl:text-3xl font-extrabold">
        Edit your profile
      </h1>
      <div class="w-full flex-1 mt-8">
        <%= render "admin/profile/form" %>

        <div class="mt-6 text-xs text-gray-600 text-center">
          <div class="mb-4">
            Unhappy? <%= button_to "Cancel my account", profile_path,
              data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" },
              method: :delete, class: "text-red-600 hover:text-red-800" %>
          </div>

          <div class='flex justify-between'>
            <%= link_to 'Change Password', profile_password_path, class: 'text-gray-900 hover:text-blue-700 dark:text-white dark:hover:text-blue-500 dark:hover:text-blue-500 hover:underline', data: { turbo_frame: '_top' } %>
            <%= link_to 'Update Avatar', avatar_admin_profile_index_path, class: 'text-gray-900 hover:text-blue-700 dark:text-white dark:hover:text-blue-500 dark:hover:text-blue-500 hover:underline', data: { turbo_frame: '_top' } %>
          </div>

          <%= link_to 'Back', profile_path, class: 'dark:text-white dark:hover:text-blue-500 dark:hover:text-blue-500 hover:underline text-indigo-600 hover:text-indigo-800', data: { turbo_frame: '_top' } %>
        </div>
      </div>
    </div>
  </div>
  <div class="flex-1 text-center hidden md:flex">
    <div class="m-12 xl:m-16 w-full bg-contain bg-center bg-no-repeat" style="background-image: url('<%= asset_path('update-profile.svg') %>');">
    </div>
  </div>
</div>

app/views/admin/profile/show.html.erb
<div class="max-w-screen-xl mx-auto bg-white dark:bg-gray-600 shadow sm:rounded-lg flex justify-center flex-1">
  <div class="w-full">
    <img
      src="https://images.unsplash.com/photo-1451187580459-43490279c0fa?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w0NzEyNjZ8MHwxfHNlYXJjaHw5fHxjb3ZlcnxlbnwwfDB8fHwxNzEwNzQxNzY0fDA&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=1080"
      alt="User Cover"
      class="rounded-t-lg w-full xl:h-[20rem] lg:h-[18rem] md:h-[16rem] sm:h-[14rem] h-[11rem]"
    />

    <div class="sm:w-[80%] w-[90%] mx-auto flex flex-row max-[550px]:flex-col">
      <%= link_to avatar_admin_profile_index_path, title: 'Click to update your avatar',
        class: "group relative inline-block lg:bottom-[5rem] sm:bottom-[4rem] bottom-[3rem]" do %>
        <% if current_user.profile_avatar.attached? %>
          <%= image_tag current_user.profile_avatar, alt: "User Profile",
            class: "lg:h-[12rem] md:h-[10rem] h-[8rem] max-[550px]:mx-auto max-[550px]:max-h-[200px] rounded-lg relative" %>
        <% else %>
          <div class="lg:w-[12rem] lg:h-[12rem] md:w-[10rem] md:h-[10rem] w-[8rem] h-[8rem] max-[550px]:mx-auto max-[550px]:max-w-[200px] max-[550px]:max-h-[200px] rounded-lg relative flex items-center justify-center bg-blue-500 text-white text-xl font-semibold">
            <%= short_name(current_user.full_name) %>
          </div>
        <% end %>
        <div class="flex items-center justify-center absolute rounded-lg inset-0 bg-black bg-opacity-80 opacity-0 group-hover:opacity-100 transition-opacity">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="text-white" viewBox="0 0 16 16">
            <path d="M9.5 2.672a.5.5 0 1 0 1 0V.843a.5.5 0 0 0-1 0zm4.5.035A.5.5 0 0 0 13.293 2L12 3.293a.5.5 0 1 0 .707.707zM7.293 4A.5.5 0 1 0 8 3.293L6.707 2A.5.5 0 0 0 6 2.707zm-.621 2.5a.5.5 0 1 0 0-1H4.843a.5.5 0 1 0 0 1zm8.485 0a.5.5 0 1 0 0-1h-1.829a.5.5 0 0 0 0 1zM13.293 10A.5.5 0 1 0 14 9.293L12.707 8a.5.5 0 1 0-.707.707zM9.5 11.157a.5.5 0 0 0 1 0V9.328a.5.5 0 0 0-1 0zm1.854-5.097a.5.5 0 0 0 0-.706l-.708-.708a.5.5 0 0 0-.707 0L8.646 5.94a.5.5 0 0 0 0 .707l.708.708a.5.5 0 0 0 .707 0l1.293-1.293Zm-3 3a.5.5 0 0 0 0-.706l-.708-.708a.5.5 0 0 0-.707 0L.646 13.94a.5.5 0 0 0 0 .707l.708.708a.5.5 0 0 0 .707 0z"></path>
          </svg>
        </div>
      <% end %>
      <div class='flex flex-col max-[550px]:items-center max-[640px]:pl-4 sm:items-start relative bottom-[3rem] min-[550px]:bottom-[0]'>
        <h1 class="mt-4 sm:mx-4 dark:text-gray-400 text-gray-800 lg:text-4xl md:text-3xl sm:text-3xl text-xl font-serif">
          <%= current_user.full_name %>
        </h1>
        <h1 class="sm:mx-4  dark:text-gray-500 text-gray-600 lg:text-2xl md:text-xl text-lg font-serif">
          <%= current_user.email %>
        </h1>
      </div>
    </div>

    <div class="xl:w-[80%] lg:w-[90%] md:w-[90%] sm:w-[85%] w-[90%] grid grid-cols-1 md:grid-cols-2 md:gap-6 mx-auto flex flex-col">
      <dl class="text-gray-900 dark:text-gray-400 divide-y divide-gray-200 dark:divide-gray-700 border-b-[1px] border-solid border-gray-200 dark:border-gray-700 md:border-none">
        <div class="flex flex-col py-3">
          <dt class="mb-1 text-gray-500 md:text-lg sm:text-md text-xs">Date Of Birth</dt>
          <dd class="text-md sm:text-lg font-semibold"><%= current_user.birth_date&.strftime("%B %d, %Y") || 'Not provided' %></dd>
        </div>
        <div class="flex flex-col py-3">
          <dt class="mb-1 text-gray-500 md:text-lg sm:text-md text-xs">Phone Number</dt>
          <dd class="text-md sm:text-lg font-semibold"><%= current_user.phone_number || 'Not provided' %></dd>
        </div>
      </dl>
      <dl class="text-gray-900 dark:text-gray-400 divide-y divide-gray-200 dark:divide-gray-700">
        <div class="flex flex-col py-3">
          <dt class="mb-1 text-gray-500 md:text-lg sm:text-md text-xs">Created at</dt>
          <dd class="text-md sm:text-lg font-semibold"><%= current_user.created_at.strftime("%B %d, %Y at %I:%M %p") %></dd>
        </div>
        <div class="flex flex-col py-3">
          <dt class="mb-1 text-gray-500 md:text-lg sm:text-md text-xs">Updated at</dt>
          <dd class="text-md sm:text-lg font-semibold"><%= current_user.updated_at.strftime("%B %d, %Y at %I:%M %p") %></dd>
        </div>
      </dl>
    </div>

    <div class="mt-6 mb-3 text-xs mx-auto space-y-4 xl:w-[80%] lg:w-[90%] md:w-[90%] sm:w-[85%] w-[90%]">
      <div class="">
        <%= button_to "Sign out",
          destroy_user_session_path, data: { turbo_method: :delete },
          method: :delete,
          class: "inline-flex items-center justify-center w-full px-4 py-2 text-sm font-medium " \
            "text-gray-900 bg-orange-200 border border-orange-200 rounded-lg hover:bg-orange-300 hover:text-primary-700 focus:outline-none " \
            "focus:ring-4 focus:ring-orange-200" %>
      </div>
  
      <div class="flex flex-col md:flex-row justify-between">
        <%= link_to 'Update Profile', edit_admin_profile_index_path, class: 'text-gray-900 hover:text-blue-700 dark:text-white dark:hover:text-blue-500 dark:hover:text-blue-500 hover:underline', data: { turbo_frame: '_top' } %>
        <%= link_to 'Update Avatar', avatar_admin_profile_index_path, class: 'text-gray-900 hover:text-blue-700 dark:text-white dark:hover:text-blue-500 dark:hover:text-blue-500 hover:underline', data: { turbo_frame: '_top' } %>
        <%= link_to 'Change Password', profile_password_path, class: 'text-gray-900 hover:text-blue-700 dark:text-white dark:hover:text-blue-500 dark:hover:text-blue-500 hover:underline', data: { turbo_frame: '_top' } %>
      </div>
    </div>
  </div>
</div>

app/views/admin/profile/update_avatar.turbo_stream.erb
<% if current_user.errors.any? %>
  <%= turbo_stream.replace 'profile_form', partial: 'admin/profile/avatar_form' %>
<% else %>
  <%= turbo_stream.replace 'redirect_frame', "<script>window.location='#{avatar_admin_profile_index_path}';</script>" %>
<% end %>