config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  scope '/admin' do
    devise_for :users, skip: [:registrations], controllers: { sessions: 'users/sessions' }

    devise_scope :user do
      get 'users/sign_up', to: 'devise/registrations#new'
      post 'users/sign_up', to: 'devise/registrations#create'
      get 'profile/password', to: 'devise/registrations#edit'
      patch 'profile/password', to: 'devise/registrations#update'
      put 'profile/password', to: 'devise/registrations#update'
      delete 'profile', to: 'devise/registrations#destroy'
    end
  end

  namespace :admin do
    root to: 'dashboard#index'

    resources :profile, only: [] do
      collection do
        get '', to: 'profile#show'
        
        get 'avatar', to: 'profile#edit_avatar'
        patch 'avatar', to: 'profile#update_avatar'
        put 'avatar', to: 'profile#update_avatar'

        get 'edit', to: 'profile#edit'
        put '', to: 'profile#update'
        patch '', to: 'profile#update'
      end
    end

    resources :users, except: [:show] do
      member do
        get '', to: 'users#show', constraints: { id: /\d+/ }, as: :user
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable

  validates :first_name, :last_name, presence: true
  validate :birth_date_range

  enum role: { user: 'user', admin: 'admin' }
  
  has_one_attached :profile_avatar
  validate :profile_avatar_content_type
  validate :profile_avatar_size


  def full_name
    [first_name, last_name].reject(&:blank?).join(' ')
  end

  # Prevent sign in for newly registered users
  def active_for_authentication?
    super && active?
  end
  
  def birth_date_range
    return unless birth_date.present?

    if birth_date > Date.today
      errors.add(:birth_date, 'cannot be in the future')
    elsif Date.today.year - birth_date.year < 18
      errors.add(:birth_date, 'must be at least 18 years old')
    end
  end

  def profile_avatar_content_type
    return unless profile_avatar.attached?

    if !profile_avatar.content_type.in?(%('image/png image/jpeg image/jpg'))
      errors.add(:avatar, 'must be a PNG or JPEG')
    end
  rescue ActiveStorage::FileNotFoundError
    errors.add(:avatar, 'could not be found')
  end

  def profile_avatar_size
    return unless profile_avatar.attached?

    if profile_avatar.byte_size > 5.megabytes
      errors.add(:avatar, 'size must be less than 5 MB')
    end
  rescue ActiveStorage::FileNotFoundError
    errors.add(:avatar, 'could not be found')
  end

  def self.ransackable_attributes(auth_object = nil)
    ["active",  "birth_date", "created_at", "current_sign_in_at", "current_sign_in_ip",
    "email", "encrypted_password", "failed_attempts", "first_name", "id",
    "id_value", "last_name", "last_sign_in_at", "last_sign_in_ip",
    "locked_at", "phone_number", "remember_created_at", "reset_password_sent_at",
    "reset_password_token", "role", "sign_in_count", "unlock_token", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["profile_avatar_attachment", "profile_avatar_blob", "full_name"]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @q = User.ransack(params[:q])  # Initialize the search query object

    @q.sorts = 'first_name asc, last_name asc' if @q.sorts.empty?

    @pagy, @users = pagy(@q.result(distinct: true), items: 10)
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def search_params
    {
      email_cont: params[:search_email],
      first_name_cont: params[:search_first_name],
      last_name_cont: params[:search_last_name]
    }.compact
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def destroy
    super do
      respond_to do |format|
        format.turbo_stream { render :destroy } # Render the Turbo Stream view
        format.html { redirect_to '/', notice: 'Signed out successfully.' }
      end
      return # Prevent further execution
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/admin/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#create</h1>
  <p>Find me in app/views/admin/users/create.html.erb</p>
</div>

app/views/admin/users/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#destroy</h1>
  <p>Find me in app/views/admin/users/destroy.html.erb</p>
</div>

app/views/admin/users/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#edit</h1>
  <p>Find me in app/views/admin/users/edit.html.erb</p>
</div>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<button class='btn-primary my-button'>Primary Button</button>

<%= search_form_for @q, url: admin_users_path, method: :get, html: { class: 'mb-4' } do |f| %>
  <div class="flex space-x-4">
    <div class="w-full">
      <%= f.label :first_name_cont, "Search by First Name", class: 'block' %>
      <%= f.text_field :first_name_cont, class: 'w-full p-2 border border-gray-300 rounded-md' %>
    </div>

    <div class="w-full">
      <%= f.label :last_name_cont, "Search by Last Name", class: 'block' %>
      <%= f.text_field :last_name_cont, class: 'w-full p-2 border border-gray-300 rounded-md' %>
    </div>

    <div class="w-full">
      <%= f.label :email_cont, "Search by Email", class: 'block' %>
      <%= f.text_field :email_cont, class: 'w-full p-2 border border-gray-300 rounded-md' %>
    </div>

    <div class="flex items-end">
      <%= f.submit "Search", class: "px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600" %>
    </div>
  </div>
<% end %>

<%= table_for User, @users, options: {
  attributes: %w(first_name:sortable last_name:sortable email:sortable birth_date my_helper_method:sortable),
} %>

<%== pagy_nav(@pagy) %>

app/views/admin/users/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#new</h1>
  <p>Find me in app/views/admin/users/new.html.erb</p>
</div>

app/views/admin/users/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#show</h1>
  <p>Find me in app/views/admin/users/show.html.erb</p>
</div>

app/views/admin/users/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#update</h1>
  <p>Find me in app/views/admin/users/update.html.erb</p>
</div>