config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  scope '/admin' do
    devise_for :users, skip: [:registrations], controllers: { sessions: 'users/sessions' }

    devise_scope :user do
      get 'users/sign_up', to: 'devise/registrations#new'
      post 'users/sign_up', to: 'devise/registrations#create'
      get 'profile/password', to: 'devise/registrations#edit'
      patch 'profile/password', to: 'devise/registrations#update'
      put 'profile/password', to: 'devise/registrations#update'
      delete 'profile', to: 'devise/registrations#destroy'
    end
  end

  namespace :admin do
    root to: 'dashboard#index'

    resources :profile, only: [] do
      collection do
        get '', to: 'profile#show'
        
        get 'avatar', to: 'profile#edit_avatar'
        patch 'avatar', to: 'profile#update_avatar'
        put 'avatar', to: 'profile#update_avatar'

        get 'edit', to: 'profile#edit'
        put '', to: 'profile#update'
        patch '', to: 'profile#update'
      end
    end

    resources :users, except: [:show] do
      member do
        get '', to: 'users#show', constraints: { id: /\d+/ }, as: :user
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="<%= flash_class(type) %>">
    <p><%= message %></p>
  </div>
<% end %>

app/views/layouts/_head_tag.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="turbo-prefetch" content="false">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_nav.html.erb
<nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
  <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl p-4">
    <%= link_to admin_root_path, class: "flex items-center space-x-3 rtl:space-x-reverse" do %>
      <%= image_tag "logo.svg", class: "h-8", alt: "Rails 7 Logo" %>
    <% end %>
    <button
      data-collapse-toggle="mega-menu-full"
      type="button"
      class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
      aria-controls="mega-menu-full"
      aria-expanded="false"
    >
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15" />
      </svg>
    </button>
    <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <button
        type="button"
        class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
        id="user-menu-button"
        aria-expanded="false"
        data-dropdown-toggle="user-dropdown"
        data-dropdown-placement="bottom"
      >
        <span class="sr-only">Open user menu</span>
        <% if current_user.profile_avatar.attached? %>
          <%= image_tag current_user.profile_avatar, alt: "User Profile",
            class: "w-8 h-8 rounded-full" %>
        <% else %>
          <div class="w-8 h-8 rounded-full flex items-center justify-center bg-blue-500 text-white text-xl font-semibold">
            <%= short_name(current_user.full_name) %>
          </div>
        <% end %>
      </button>
      <!-- Dropdown menu -->
      <div
        class="z-50 my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600 hidden"
        id="user-dropdown"
        style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(200.8px, 62.4px, 0px);"
        aria-hidden="true"
        data-popper-placement="bottom"
      >
        <div class="px-4 py-3">
          <span class="block text-sm text-gray-900 dark:text-white">Bonnie Green</span>
          <span class="block text-sm text-gray-500 truncate dark:text-gray-400">name@flowbite.com</span>
        </div>
        <ul class="py-2" aria-labelledby="user-menu-button">
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Dashboard</a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
          </li>
          <li>
            <a data-controller="theme-toggle"
              data-svg='false' href="#"
              data-action="click->theme-toggle#toggleTheme"
              class='block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white'>
              <span class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">
                Toggle Theme
              </span>
            </a>
          </li>
          <li>
            <%= link_to 'Profile', profile_path,
              class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign out</a>
          </li>
        </ul>
      </div>
    </div>
    <div id="mega-menu-full" class="items-center justify-between font-medium hidden w-full md:flex md:w-auto md:order-1">
      <ul class="flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a
            href="#"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700"
            aria-current="page"
          >
            Home
          </a>
        </li>
        <li>
          <button
            id="mega-menu-full-dropdown-button"
            data-collapse-toggle="mega-menu-full-dropdown"
            class="flex items-center justify-between w-full py-2 px-3 text-gray-900 rounded md:w-auto hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700"
          >
            Company
            <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
            </svg>
          </button>
        </li>
        <li>
          <a
            href="#"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700"
          >
            Marketplace
          </a>
        </li>
        <li>
          <a
            href="#"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700"
          >
            Resources
          </a>
        </li>
        <li>
          <a
            href="#"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700"
          >
            Contact
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div id="mega-menu-full-dropdown" class="mt-1 border-gray-200 shadow-sm bg-gray-50 md:bg-white border-y dark:bg-gray-800 dark:border-gray-600 hidden">
    <div class="grid max-w-screen-xl px-4 py-5 mx-auto text-gray-900 dark:text-white sm:grid-cols-2 md:px-6">
      <ul>
        <li>
          <a href="#" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
            <div class="font-semibold">Online Stores</div>
            <span class="text-sm text-gray-500 dark:text-gray-400">Connect with third-party tools that you're already using.</span>
          </a>
        </li>
        <li>
          <a href="#" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
            <div class="font-semibold">Segmentation</div>
            <span class="text-sm text-gray-500 dark:text-gray-400">Connect with third-party tools that you're already using.</span>
          </a>
        </li>
        <li>
          <a href="#" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
            <div class="font-semibold">Marketing CRM</div>
            <span class="text-sm text-gray-500 dark:text-gray-400">Connect with third-party tools that you're already using.</span>
          </a>
        </li>
      </ul>
      <ul>
        <li>
          <a href="#" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
            <div class="font-semibold">Online Stores</div>
            <span class="text-sm text-gray-500 dark:text-gray-400">Connect with third-party tools that you're already using.</span>
          </a>
        </li>
        <li>
          <a href="#" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
            <div class="font-semibold">Segmentation</div>
            <span class="text-sm text-gray-500 dark:text-gray-400">Connect with third-party tools that you're already using.</span>
          </a>
        </li>
        <li>
          <a href="#" class="block p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
            <div class="font-semibold">Marketing CRM</div>
            <span class="text-sm text-gray-500 dark:text-gray-400">Connect with third-party tools that you're already using.</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_redirect.html.erb
<%# This partial will execute a JavaScript redirect %>
<script>
  window.location.href = '<%= path %>';
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails 7 Tailwind</title>
    <%= render "layouts/head_tag" %>
  </head>

  <body>
    <turbo-frame id="redirect_frame"></turbo-frame>
    <div class="min-h-screen antialiased bg-gray-100 dark:bg-gray-900">
      <%#= render 'layouts/navigation' %>
      <%= render 'layouts/nav' %>

      <%#= render 'layouts/sidebar' %>

      <main class="mt-[73px] md:mt-[65px] px-4 py-5 h-auto">
        <%= render "layouts/flash" %>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails 7 Tailwind</title>
    <%= render "layouts/head_tag" %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>